[project]
timeout = 60

[[tests]]
name = "01"
input = ["python3", "runxv6.py", "ps"]
expected = """
$ ps
PID=1 NAME=init SIZE=24576 STATE=sleep
PID=2 NAME=sh SIZE=28672 STATE=sleep
PID=3 NAME=ps SIZE=24576 STATE=run
"""
rubric = 5

