[project]
timeout = 300

[[tests]]
name = "01"
input = ["python3", "runxv6.py", "head README"]
expected = """
head README
xv6 is a re-implementation of Dennis Ritchie's and Ken Thompson's Unix
Version 6 (v6).  xv6 loosely follows the structure and style of v6,
but is implemented for a modern RISC-V multiprocessor using ANSI C.

ACKNOWLEDGMENTS

xv6 is inspired by John Lions's Commentary on UNIX 6th Edition (Peer
to Peer Communications; ISBN: 1-57398-013-7; 1st edition (June 14,
2000)).  See also https://pdos.csail.mit.edu/6.1810/, which provides
pointers to on-line resources for v6.
"""
rubric = 5

[[tests]]
name = "02"
input = ["python3", "runxv6.py", "head -n 3 README"]
expected = """
head -n 3 README
xv6 is a re-implementation of Dennis Ritchie's and Ken Thompson's Unix
Version 6 (v6).  xv6 loosely follows the structure and style of v6,
but is implemented for a modern RISC-V multiprocessor using ANSI C.
"""
rubric = 5

[[tests]]
name = "03"
input = ["python3", "runxv6.py", "listtest > listtest.txt; head -n 2 README listtest.txt"]
expected = """
listtest > listtest.txt; head -n 2 README listtest.txt
== > README <==
xv6 is a re-implementation of Dennis Ritchie's and Ken Thompson's Unix
Version 6 (v6).  xv6 loosely follows the structure and style of v6,
== > listtest.txt <==
[google.com, 142.251.46.174]
[usfca.edu, 23.185.0.2]
"""
rubric = 5

[[tests]]
name = "04"
input = ["python3", "runxv6.py", "cat README | head -n 3"]
expected = """
cat README | head -n 3
xv6 is a re-implementation of Dennis Ritchie's and Ken Thompson's Unix
Version 6 (v6).  xv6 loosely follows the structure and style of v6,
but is implemented for a modern RISC-V multiprocessor using ANSI C.
"""
rubric = 5

[[tests]]
name = "05"
input = ["python3", "runxv6.py", "tail README"]
expected = """
tail README
(kaashoek,rtm@mit.edu).  The main purpose of xv6 is as a teaching
operating system for MIT's 6.1810, so we are more interested in
simplifications and clarifications than new features.

BUILDING AND RUNNING XV6

You will need a RISC-V "newlib" tool chain from
https://github.com/riscv/riscv-gnu-toolchain, and qemu compiled for
riscv64-softmmu.  Once they are installed, and in your shell
search path, you can run "make qemu".
"""
rubric = 10

[[tests]]
name = "06"
input = ["python3", "runxv6.py", "listtest > listtest.txt; tail -n 2 README listtest.txt"]
expected = """
listtest > listtest.txt; tail -n 2 README listtest.txt
== > README <==
riscv64-softmmu.  Once they are installed, and in your shell
search path, you can run "make qemu".
== > listtest.txt <==
[openai.com, 13.107.238.57]
[usfca.edu, 23.185.0.2]
"""
rubric = 10

[[tests]]
name = "07"
input = ["python3", "runxv6.py", "cat README | tail -n 3"]
expected = """
cat README | tail -n 3
https://github.com/riscv/riscv-gnu-toolchain, and qemu compiled for
riscv64-softmmu.  Once they are installed, and in your shell
search path, you can run "make qemu".
"""
rubric = 10

[[tests]]
name = "08"
input = ["python3", "runxv6.py", "seq 5"]
expected = """
seq 5
1
2
3
4
5
"""
rubric = 5

[[tests]]
name = "09"
input = ["python3", "runxv6.py", "seq"]
expected = """
seq
usage: seq [-p prefix] last
       seq [-p prefix] first last
       seq [-p prefix] first inc last
"""
rubric = 5

[[tests]]
name = "10"
input = ["python3", "runxv6.py", "seq 30 -2 20"]
expected = """
seq 30 -2 20
30
28
26
24
22
20
"""
rubric = 5


[[tests]]
name = "11"
input = ["python3", "runxv6.py", "seq -p foo_ 5"]
expected = """
seq -p foo_ 5
foo_1
foo_2
foo_3
foo_4
foo_5
"""
rubric = 5


[[tests]]
name = "12"
input = ["python3", "runxv6.py", "seq -p foo_ 5"]
expected = """
seq -p foo_ 5
foo_1
foo_2
foo_3
foo_4
foo_5
"""
rubric = 5

[[tests]]
name = "13"
input = ["python3", "runxv6.py", "seq -p foo_ 5"]
expected = """
seq -p foo_ 5
foo_1
foo_2
foo_3
foo_4
foo_5
"""
rubric = 5

[[tests]]
name = "14"
input = ["python3", "runxv6.py", "seq 1003 | cat -n | tail"]
expected = """
seq 1003 | cat -n | tail
   994  994
   995  995
   996  996
   997  997
   998  998
   999  999
  1000  1000
  1001  1001
  1002  1002
  1003  1003
"""
rubric = 5

[[tests]]
name = "15"
input = ["python3", "runxv6.py", "seq -p id_ 100 -1 0 | head -n 20 | tail -n 5 | sort | cat -n"]
expected = """
seq -p id_ 100 -1 0 | head -n 20 | tail -n 5 | sort | cat -n
     1  id_81
     2  id_82
     3  id_83
     4  id_84
     5  id_85
"""
rubric = 10

[[tests]]
name = "16"
input = ["python3", "runxv6.py", "seq -p id_ 100 -1 0 | head -n 20 | tail -n 5 | sort | cat -n | wc -l"]
expected = """
seq -p id_ 100 -1 0 | head -n 20 | tail -n 5 | sort | cat -n | wc -l
5
"""
rubric = 5
